### ISSUE TITLE
请问怎么在fragment中切换fragment?

### ISSUE THREAD

**Issue by findfeels** [FadedYu/Framework_Android#1]
请问怎么在fragment中切换fragment?
卡了我好久。。。技术不行，无奈只能上来求救。
比如你的程序中的我的界面，点击用户怎么切换到另一个fragment，整体布局不变（tab不变，只是切换中间的页面）。
可以给个代码或思路吗？

**Comment by findfeels** [comment]
我试着调用了startFragment(new Home3Fragment());
但都是提示：
Process: com.bonait.bnframework, PID: 21444
    java.lang.IllegalArgumentException: No view found for id 0x7f080032 (com.bonait.bnframework:id/bnframework) for fragment Home3Fragment{2e129298 #4 id=0x7f080032 Home3Fragment}

**Comment by YuiGod** [comment]
@findfeels 我不建议在BottomNavigation的fragment界面中，BottomNavigation的界面有多个fragment平行切换，在里面点击replace新的fragment（tab不变，只是改变中间的页面），这样会有很多的缺陷，比如返回上一层是退出BottomNavigation的界面呢，还是返回点击的那个fragment呢？
       
事实上也没有App会这么做。最好也最简单的法是点击后跳转一个新的activity。
      
 如果非要写的话，可以这样写：
第一步，在myFragment的layout最外层添加`android:id="@+id/myFragment"` ；
第二步，在想要跳转方法写上

> getFragmentManager()
.beginTransaction()
.replace(R.id.myFragment,new Home3Fragment())
.commit();

但是这样有个缺点是要自己写代码把fragment填充到fragment堆栈里面去，才能返回上一层。并且不受QMUI的控制。

还有startFragment(new Home3Fragment());报错的原因是找不到跳转界面的容器。
要最外层的activity要继承QMUIFragmentActivity才可以使用，并且重写getContextViewId()方法，且在该layout最外层添加`android:id="@+id/textActivity"` 然后return这个id。
`
@Override
    protected int getContextViewId() {
        return R.id.textActivity;
    }
`

我最后的建议是，跳转新的activity吧，最简单的方式了。
还有一点是，我的项目没有像QMUI那样使用只有一个主activity多个fragment的架构。所以暂时没有继承QMUIFragmentActivity。最好可以根据业务功能模块需要添加fragment的组合跳转。
（抱歉这么久才看到，因为这个项目我鸽了哈哈，逃~）
